---
  before_script:
    - yarn
  branches:
    only:
      - master
  cache: yarn
  language: node_js
  node_js:
    - "12"
  script:
    - "yarn test"
  after_success:
    - bash <(curl -s https://codecov.io/bash)
