import { LoanEventIds, LoanEventTypes } from './PropertyDetailsSideBar';

export const Loan = {
	show: true,
	summary:
		'$7.5 m 1st Mortgage with <span class="name">BEAR 2006-PWR12</span> at  5.8% (Fixed) ',
	summaryLink:
		'$7.5 m 1st Mortgage with <a href="/#/lender-profile/69cb529b-298a-4263-b884-a7a653a7f363/summary"><span class="name">BEAR 2006-PWR12</span></a> at  5.8% (Fixed) ',
	loanStatus: 'Troubled',
	loanType: '1st Mortgage',
	qualifier: null,
	debtYield: '',
	totalLoanReserve: '',
	loanQualifier: '',
	loanAmount: '$7.5 m',
	loanId: 88636,
	interestRate: '5.8% Fixed',
	term: '120 Months',
	appraisal: '$9,398,496',
	originator: 'Wells Fargo',
	lender: 'C-III Asset Management OBO BEAR 2006-PWR12',
	lenderGroup: 'CMBS',
	mortgageBroker: null,
	loanAmortization: 'Partial Interest Only',
	originalLTV: '79.8%',
	loanDescription: '1.48x',
	origination: '06/01/2006',
	defeasance: '05/01/2009',
	prepayment: '02/01/2016',
	originalMaturity: '06/01/2016',
	comments: 'Trouble;',
	controlNumber: null,
	loanEventId: LoanEventIds.SpecialServicing,
	loanEvent: LoanEventTypes.SpecialServicing,
	loanEventDt: '09/20/2012',
	watchlistComments:
		'Subject is a retail property located in Tappahannock, VA. Q2 2012, occupancy is 77.99% and NCF DSCR is at 1.06x. \n\n06/04/2013: Property is on the watch list because NCF DSCR has dropped below threshold of 1.1x and occupancy is below 80%. The borrower is marketing the vacant space. Will continue to monitor property.',
	watchlistCommentsDt: '06/01/2013',
	specialServicerComments:
		"Loan transferred to special servicing 9/2012. Property condition reports show significant deferred maintenance (roofs and parking lot). Borrower indicated certain repairs were underway.  Borrower stated it will be unable to refinance the debt at matu     rity in 6/2016.  Borrower continues to remit Debt Service payments.  Borrower's request for a short sale to an unrelated third party has been approved by the Special Servicer.  Consummation of the transaction anticipated in 7/2016.",
	specialServicerCommentsDt: '06/01/2016',
	reoComments: null,
	reoCommentsDt: null,
	outstandingBalanceUSD_amt: '$6,593,401',
	outstandingBalanceDt: '2019-07-01T00:00:00',
	formatFinancingSummary: () => '',
	formatCurrency: () => '',
	formatInterest: () => '',
	showDate: () => false,
	formatDate: () => '',
	formatFinancingComments: () => '',
	formatLoanAmount: () => '',
	formatQualifier: () => '',
};
